baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Daniele Quattrociocchi'
theme = 'PaperMod'
[params]
    subtitle = 'The Best Widgets on Earth'
    [params.contact]
    email = 'info@example.org'
    phone = '+1 202-555-1212'
    
